### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Akshit-Trivedi-Inferenz**

### CODE REVIEW

**Review by vishal-katheriya-inferenz — APPROVED** [review]
perfect

**Review by vishal-katheriya-inferenz — DISMISSED** [review]
ok

**Review by vishal-katheriya-inferenz — DISMISSED** [review]

**Review by pinkal-rathod-inferenz — APPROVED** [review]
awsm

**Review by vishal-katheriya-inferenz — CHANGES_REQUESTED** [review]
test

**Review by Akshit-Trivedi-Inferenz — COMMENTED** [review]
done

**Review by vishal-katheriya-inferenz — APPROVED** [review]

**Pull request merged**
